import type { AppData } from "../../scripts/gamesmanUniTypes";

export const defaultApp: AppData = {
    externalDataSources: {
        gamesmanUniGitHubRepositoryDataSource: "https://api.github.com/repos/GamesCrafters/GamesmanUni",
        onePlayerGamesDataSource: "https://nyc.cs.berkeley.edu/puzzles",
        twoPlayersGamesDataSource: "https://nyc.cs.berkeley.edu/universal/v1/games",
    },
    game: {
        author: "",
        description: "",
        history: [],
        id: "",
        instructions: "",
        name: "",
        options: {
            showDate: false,
            showInstruction: false,
            showNextMoves: true,
            showNextMoveDeltaRemotenesses: true,
            showNextMoveHints: true,
            showOptions: false,
            showStopWatch: false,
            showTime: false,
            showVisualValueHistory: true,
        },
        players: [],
        preFetchedRawPositionDatas: {},
        round: {
            availableMoves: [],
            id: 0,
            move: "",
            moveValue: "",
            player: {
                id: 0,
                name: "",
            },
            position: "",
            positionValue: "",
            remoteness: Number.POSITIVE_INFINITY,
        },
        status: "",
        turn: 0,
        type: "",
        variant: {
            description: "",
            id: "",
            status: "",
            startPosition: "",
        },
        variants: [],
    },
    games: [],
    latestCommitHistory: [],
    preferences: {
        theme: "light",
        locale: "en",
        fallbackLocale: "en",
    },
    puzzles: [],
    version: <string>import.meta.env.PACKAGE_VERSION,
};
